import NavBar from "./components/navbar";

export default function App() {
  return (
    <>
      <NavBar/>
      <h1>asjfkasjfkasfjlksafjsakfjlsakfjksalf</h1>
      <h1>asjfkasjfkasfjlksafjsakfjlsakfjksalf</h1>
      <h1>asjfkasjfkasfjlksafjsakfjlsakfjksalf</h1>
      <h1>asjfkasjfkasfjlksafjsakfjlsakfjksalf</h1>
      <h1>asjfkasjfkasfjlksafjsakfjlsakfjksalf</h1>
      <h1>asjfkasjfkasfjlksafjsakfjlsakfjksalf</h1>
      <h1>asjfkasjfkasfjlksafjsakfjlsakfjksalf</h1>
      <h1>asjfkasjfkasfjlksafjsakfjlsakfjksalf</h1>
      <h1>asjfkasjfkasfjlksafjsakfjlsakfjksalf</h1>
      <h1>asjfkasjfkasfjlksafjsakfjlsakfjksalf</h1>
      <h1>asjfkasjfkasfjlksafjsakfjlsakfjksalf</h1>
      <h1>asjfkasjfkasfjlksafjsakfjlsakfjksalf</h1>
      <h1>asjfkasjfkasfjlksafjsakfjlsakfjksalf</h1>
      <h1>asjfkasjfkasfjlksafjsakfjlsakfjksalf</h1>
      <h1>asjfkasjfkasfjlksafjsakfjlsakfjksalf</h1>
      <h1>asjfkasjfkasfjlksafjsakfjlsakfjksalf</h1>
      <h1>asjfkasjfkasfjlksafjsakfjlsakfjksalf</h1>
      <h1>asjfkasjfkasfjlksafjsakfjlsakfjksalf</h1>
      <h1>asjfkasjfkasfjlksafjsakfjlsakfjksalf</h1>
      <h1>asjfkasjfkasfjlksafjsakfjlsakfjksalf</h1>
      <h1>asjfkasjfkasfjlksafjsakfjlsakfjksalf</h1>
      <h1>asjfkasjfkasfjlksafjsakfjlsakfjksalf</h1>
      <h1>asjfkasjfkasfjlksafjsakfjlsakfjksalf</h1>
      <h1>asjfkasjfkasfjlksafjsakfjlsakfjksalf</h1>
      <h1>asjfkasjfkasfjlksafjsakfjlsakfjksalf</h1>
      <h1>asjfkasjfkasfjlksafjsakfjlsakfjksalf</h1>
      <h1>asjfkasjfkasfjlksafjsakfjlsakfjksalf</h1>
      <h1>asjfkasjfkasfjlksafjsakfjlsakfjksalf</h1>
      <h1>asjfkasjfkasfjlksafjsakfjlsakfjksalf</h1>
      <h1>asjfkasjfkasfjlksafjsakfjlsakfjksalf</h1>
      <h1>asjfkasjfkasfjlksafjsakfjlsakfjksalf</h1>
      <h1>asjfkasjfkasfjlksafjsakfjlsakfjksalf</h1>
      <h1>asjfkasjfkasfjlksafjsakfjlsakfjksalf</h1>
      <h1>asjfkasjfkasfjlksafjsakfjlsakfjksalf</h1>
      <h1>asjfkasjfkasfjlksafjsakfjlsakfjksalf</h1>
      <h1>asjfkasjfkasfjlksafjsakfjlsakfjksalf</h1>
      <h1>asjfkasjfkasfjlksafjsakfjlsakfjksalf</h1>
      <h1>asjfkasjfkasfjlksafjsakfjlsakfjksalf</h1>
      <h1>asjfkasjfkasfjlksafjsakfjlsakfjksalf</h1>
      <h1>asjfkasjfkasfjlksafjsakfjlsakfjksalf</h1>
    </>
  )
}